# Generated by Django 4.0.6 on 2022-07-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
    ]
