# Generated by Django 4.0.6 on 2022-07-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='group',
        ),
    ]
