# Generated by Django 4.0.6 on 2022-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_filehandler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('PERS', 'PERSONAL'), ('CCA', 'CCA'), ('MODS', 'MODULE'), ('PROJ', 'PROJECT')], default='PERS', max_length=10),
        ),
    ]
