# Generated by Django 4.0.6 on 2022-07-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_filehandler'),
        ('task', '0002_alter_task_taskgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='organisation',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
