# Generated by Django 4.0.6 on 2022-07-19 08:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=225)),
                ('agenda', models.CharField(max_length=225)),
                ('dates', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=225)),
                ('meeting_link', models.URLField(max_length=225, null=True)),
                ('meeting_minutes', models.TextField()),
            ],
            options={
                'ordering': ('-dates', '-start_time'),
            },
            managers=[
                ('upcomingobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
