# Generated by Django 4.0.6 on 2022-07-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meeting',
            managers=[
            ],
        ),
    ]
