# Generated by Django 4.0.6 on 2022-07-19 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_meeting_options_remove_meeting_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='dates',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 9, 25, 42, 170748, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_minutes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
