# Generated by Django 4.0.6 on 2022-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_meeting_dates_alter_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-dates', '-start_time')},
        ),
    ]
