# Generated by Django 4.0.6 on 2022-07-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('dates', '-start_time')},
        ),
    ]
