# Generated by Django 4.0.6 on 2022-07-20 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_alter_meeting_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 17, 43, 1, 916227, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
